version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"  # Expose FastAPI on port 8000
    networks:
      - app-network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"  # Expose Streamlit on port 8501
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
