services:
  - name: fastapi-service
    type: web
    env: docker
    dockerfile_path: Dockerfile.fastapi
    build_dir: .
    env_vars:
      - key: PORT
        value: "8000"
    plan: free
    regions:
      - oregon
    start_command: gunicorn -w 4 -b 0.0.0.0:8000 app:app

  - name: streamlit-service
    type: web
    env: docker
    dockerfile_path: Dockerfile.streamlit
    build_dir: .
    env_vars:
      - key: PORT
        value: "8501"
    plan: free
    regions:
      - oregon
    start_command: streamlit run bot.py --server.port 8501 --server.address 0.0.0.0
